
@isTest
private class DemoControllerTests {
@isTest static void testGetAppVersion1() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion2() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion3() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion4() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion5() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion6() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion7() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion8() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion9() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion10() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion11() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion12() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion13() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion14() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion15() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion16() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion17() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion18() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion19() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion20() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion21() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion22() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion23() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion24() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion25() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion26() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion27() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion28() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion29() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion30() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion31() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion32() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion33() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion34() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion35() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion36() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion37() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion38() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion39() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion40() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion41() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}
@isTest static void testGetAppVersion42() {
    DemoController demo = new DemoController();
    System.assertEquals(demo.getAppVersion(), '1.0.0');
}

}
